### ISSUE TITLE
Test server crashing (on GM layer)

### ISSUE THREAD

**Issue by audev** [npct/pct-shiny#435]
I've just pushed the latest build for the GM layer to the test server.
http://npct0.vs.mythic-beasts.com/greater-manchester/

Last week all worked fine (aside from some connection issues esp. on Firefox). 
Now it seems to crash when:

- The Trip data mode is set to "All"
- An action is triggered

@nikolai-b  Could this be linked to the changes in labels for the layer? I don't see any other relevant changes recently.

**Comment by JDWoodcock** [comment]
please can @nikolai-b or @Robinlovelace have a look at this as we would like to show new layer in Manchester on Monday

**Comment by nikolai-b** [comment]
I struggling to re-create this issue.  I believe it my well be a dup of https://github.com/npct/pct-shiny/issues/433#issuecomment-259302479 which has been fixed a day ago in https://github.com/npct/pct-shiny/commit/31f67f2b4bf25fbff41bd9eb76c85649ede69653.  Please can you confirm if this is still an issue and the steps required to re-create it?

On a side-note http://npct0.vs.mythic-beasts.com is not designed to be reliable, it is designed to be a test server.  Strongly suggest we should only be showing / demoing things on www.pct.bike as that is more stable and should never be broken.  If we are happy with the state of the test server (npct0) then lets deploy it to www.pct.bike today!

**Comment by JDWoodcock** [comment]
thanks for looking when I go to all trips and select lines it crahses and disconnects from server
[test.docx](https://github.com/npct/pct-shiny/files/587340/test.docx)
As I can't get it to work I dont know if I am happy with it or not! However, even if the numbers look good there would be much more work before we could put it on the live server. this demoing is to a tech group of experts- to get feedback on what we have done- it is not close to being shown to public

**Comment by nikolai-b** [comment]
Thanks, that makes sense why it is not on production.
The issue is due to the lines data missing a CRS, I've put in a hacky fix.

There is a separate problem that if you visualize the commuting lines then change to All trips the commuting lines are still shown.  The routes and route network work.  Let me know if this is works as expected.

**Comment by JDWoodcock** [comment]
thanks but I am still getting it crashing when I try and see lines on the 'all-trips' layer

**Comment by audev** [comment]
Also crashing for me. If it's something about the build, I can rebuild any time; but not sure what the CRS you mention is.

**Comment by audev** [comment]
Displaying fine now, thanks @nikolai-b

**Comment by nikolai-b** [comment]
I've fixed this by giving the l data a proj4string / CRS.  Not sure what your build process is but it was missing this and that was causing the error, I've fixed it using:

```R
> l <-  readRDS("pct-data/greater-manchester/all-trips/l.Rds")
> proj4string(l) <- CRS("+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 ")
> saveRDS(l, "pct-data/greater-manchester/all-trips/l.Rds")
```

**Comment by JDWoodcock** [comment]
thanks
