### ISSUE TITLE
Crash on near market scenario - test server

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#710]
Heads-up @AnnaGoodman1 selecting the near market scenario on the test server seems to crash the app. I think there were a few other issues with #668 which @nikolai-b said may need a bit of work and which I didn't test, hence holding horses on that one.

**Comment by AnnaGoodman1** [comment]
probably as the relevant region does not yet have the data, as I am uploading the files now (but will take a while). Just uploading isle of wight

**Comment by AnnaGoodman1** [comment]
so it works for me locally, but not on test server. I think as the files I have pushed to github for isle of wight need to be moved to the server, by e.g. @nikolai-b ?

also i do now always get the 'thinking' circle even after changin scenarios

![image](https://user-images.githubusercontent.com/11818225/56193620-fcef2480-6028-11e9-84e2-a0660768ded7.png)

**Comment by AnnaGoodman1** [comment]
oh sorry, my mistake for merging near market branch, v. sorry @nikolai-b & @Robinlovelace

**Comment by Robinlovelace** [comment]
Can always revert it so now worries.

**Comment by nikolai-b** [comment]
@AnnaGoodman1 to update the data we just update the data SHA to what ever version we want from https://github.com/npct/pct-outputs-regional-R e.g. see https://github.com/npct/pct-shiny/commit/25f7db6bb3b83be8b8018e9b08dfb80f9168200e

Now it works for LSOA Near Market, I'm assuming the MSOA Near Market isn't ready yet (as that still crashes).  I've uploaded the tiles so on Near Market the Cycling Flows: Route Network (LSOA, image) also works.

**Comment by Robinlovelace** [comment]
Many thanks @nikolai-b, it sounds like it's primarily, if not only, a data issue now. Please let us know when the data is updated @AnnaGoodman1 and I can update the SHA.

**Comment by Robinlovelace** [comment]
Update: I no longer think it's just a data issue. Avon and Isle of Wight are both crashing, despite the data SHA having been updated in https://github.com/npct/pct-shiny/commit/25f7db6bb3b83be8b8018e9b08dfb80f9168200e

Heads-up @AnnaGoodman1, @usr110, @nikolai-b: any ideas what is going on?

**Comment by Robinlovelace** [comment]
Update: I see it is still most likely a data issue. The MSOA level data has not been pushed yet. Please confirm @AnnaGoodman1. Thanks for this fantastic work and sorry for the false alarm. I imagine we can close this issue once the data finishes uploading.

**Comment by Robinlovelace** [comment]
Also to note: I tested the LSOA Near Market scenario in Cheshire and it worked fine: only at the MSOA level does it seem to be crashing.

**Comment by AnnaGoodman1** [comment]
um, I hope just as msoa files not yet uploaded, but i am worried that IOW also seems to crash on test server despite having files...though works locally on my machine...will try to look into this more tomorrow. Can I check, is the test server accessing the latest versions of what is in regional-outputs-R?

**Comment by Robinlovelace** [comment]
> Can I check, is the test server accessing the latest versions of what is in regional-outputs-R?

I believe so, yes. I noticed IoW crashing on MSOA also, so may be double checking the data.

**Comment by AnnaGoodman1** [comment]
new data al uploaded, still crashing on test server but not when I run locally. does it run locally ok for others? if not, what error does it give? or is there a way to see what error test server is finding?

**Comment by nikolai-b** [comment]
Hi,
If it is working locally can you confirm that:

1) your local `pct-outputs-regional-R` matches what is on Github
2) That the SHA in https://github.com/npct/pct-shiny/blob/master/outputs_regional_sha matches the latest in https://github.com/npct/pct-outputs-regional-R

Note that it can take 10 mins + for the server to download the data after pushing to pct-shiny, you can see if it is ready by the green tick on https://github.com/npct/pct-shiny/commits/master 
![Screenshot from 2019-04-17 18-00-34](https://user-images.githubusercontent.com/6289830/56306568-bb4e9e80-613a-11e9-929c-bc5aedbd4f41.png) which is the deploy.

I can see that the data SHA is outdated so I've made https://github.com/npct/pct-shiny/pull/714 for someone to review (and merge) :smile:

**Comment by Robinlovelace** [comment]
Could it be that the data is not downloading properly on the server? We've had a few issues with `git-lfs` in the past...

**Comment by nikolai-b** [comment]
I don't think there is any issue, after you've merged it works on the test server for me.  If we notice other problems would you mind making a new issue so it is easy to track what is happening.  I'm closing this as IoW and other regions no longer crash on near market :tada:

**Comment by Robinlovelace** [comment]
Confirmed: that seems to have fixed it.
