### ISSUE TITLE
pct down? (not loading in Firefox)

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#755]
Hi all, I'm demo-ing PCT in half an hour or so and I am struggling to get the map to open on Firefox for any areas (hangs and then returns 502 Bad Gateway The server returned an invalid or incomplete response.')
. IE seems ok at the moment & the test server is my fallback but wondered if anyone else was having problems - @Robinlovelace @JDWoodcock @AnnaGoodman1 @nikolai-b @usr110 @mem48 ?

**Comment by JDWoodcock** [comment]
quick test found it working ok for me on FF.

**Comment by RachelAldred** [comment]
Thanks, hopefully it's just a glitch on my laptop, just got a bit nervous!

**Comment by JDWoodcock** [comment]
i think there is a rule about half of bugs are detected when demoing?

**Comment by mem48** [comment]
I'm getting the same error on FireFox

**Comment by mem48** [comment]
The hompage works, but the maps do not

**Comment by AnnaGoodman1** [comment]
same for me, not working on ff

**Comment by nikolai-b** [comment]
What error are you getting?  Is anything logged in the console https://developer.mozilla.org/en-US/docs/Tools/Browser_Console#Opening_the_Browser_Console

From the server logs it looks like we got hit by #746 again :disappointed: 

![memory-day2](https://user-images.githubusercontent.com/6289830/60988449-8c138c00-a33b-11e9-9522-e6202c5a2306.png)

This has been fixed but I haven't had time to deploy to production.  I'll try my best to get it live this evening. Did you manage to demo @RachelAldred ?

**Comment by RachelAldred** [comment]
Yes it was fine on internet explorer on the room PC :)

**Comment by nikolai-b** [comment]
Great, sorry this same issue happened again.  Do we have a place where we put upcoming demos / large events?  It would be good so I can keep a closer :eye: on pct at such times.

I think it is likely a duplicate of #746 but it only took npt2 down (from the memory it looks like it restarted but I will double check later), our other server npt1 stayed up.

We have a load balancer which sends you to npt1 or npt2 and sets a cookie so if you used FF and got an npt2 cookie and npt2 goes down then the site will be down BUT if you clear your cookies, use another browser etc. then our load balancer would direct you to npt1 (as it would recognise that npt2 would be down).

I'll leave this open for a bit as I think there might be some actionable things we could do like

- [ ] check the logs to see if npt2 restarted properly
- [ ] see if we can ignore the cookie if the server is down

**Comment by RachelAldred** [comment]
Thanks, Megan and I were having problems with PCT on Firefox again today but I've just cleared cookies and it worked again for me. We are training tomorrow so will ask people to use another browser as generally we would use Firefox, so I guess it might be safer to stick to something else. On sharing dates of future heavy use for training etc. - this is a good idea, thanks. What is the best way to do this do you think?

**Comment by RachelAldred** [comment]
Megan still having problems with Firefox (server disconnect) even after clearing cookies, but IE ok.

**Comment by nikolai-b** [comment]
@RachelAldred I believe this is more likely #759

**Comment by Robinlovelace** [comment]
Closing as duplicate of #759 I think.
