### ISSUE TITLE
Server reliability

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#759]
hi all
not sure best way to notify but given potential issues to send out reminder there is pct training tomorrow so hopefully will run smoothly
@nikolai-b

**Comment by JDWoodcock** [comment]
on that I am noticing some problems loading for London as is Ali
The application unexpectedly exited.


Diagnostic information is private. Please ask your system admin for permission if you need to check the R logs. shiny-server-client.min.js:1:24931
Mon Jul 15 2019 14:39:28 GMT+0100 (British Summer Time) [INF]: Connection closed. Info: {"type":"close","code":4503,"reason":"The application unexpectedly exited","wasClean":true} shiny-server-client.min.js:1:21781
Mon Jul 15 2019 14:39:28 GMT+0100 (British Summer Time) [DBG]: SockJS connection closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 14:39:28 GMT+0100 (British Summer Time) [DBG]: Channel 0 is closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 14:39:28 GMT+0100 (British Summer Time) [DBG]: Removed channel 0, 0 left shiny-server-client.min.js:1:5353

**Comment by JDWoodcock** [comment]
ok now getting this for Cambridgeshire
Mon Jul 15 2019 15:52:16 GMT+0100 (British Summer Time) [INF]: Connection opened. http://pct.bike/m/?r=cambridgeshire shiny-server-client.min.js:1:21781
Mon Jul 15 2019 15:52:16 GMT+0100 (British Summer Time) [DBG]: Open channel 0 shiny-server-client.min.js:1:5353
The application unexpectedly exited.



Diagnostic information is private. Please ask your system admin for permission if you need to check the R logs. shiny-server-client.min.js:1:24931
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [INF]: Connection closed. Info: {"type":"close","code":4503,"reason":"The application unexpectedly exited","wasClean":true} shiny-server-client.min.js:1:21781
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [DBG]: SockJS connection closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [DBG]: Channel 0 is closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [DBG]: Removed channel 0, 0 left shiny-server-client.min.js:1:5353

**Comment by Robinlovelace** [comment]
Working OK for me. Could you confirm it's still playing up and outline the steps that lead to the crash? Just got the following for London no problem:

![image](https://user-images.githubusercontent.com/1825120/61227592-7f68ac80-a71c-11e9-917b-a80b24eba3dc.png)

**Comment by RachelAldred** [comment]
I just got a disconnect on London schools layer using IE, trying to show the vector flow layer.
![image](https://user-images.githubusercontent.com/11818218/61227801-e9815180-a71c-11e9-80b1-fb87adeb3b48.png) Second time trying I got a different error message.
![image](https://user-images.githubusercontent.com/11818218/61227944-36fdbe80-a71d-11e9-9d8e-ebf7f00bb3d4.png)

**Comment by Robinlovelace** [comment]
It's working fine for me still. Definitely worth checking the server logs to see what's going on. Does it happen instantly? If you could set out a typical scenario when a crash happens, that would be useful, e.g.:

1. Go to http://www.pct.bike/m/?r=london
2. Click on the clickable route network option under Cycling Flows
3. ... e.g. wait a few minutes.
4. Crash

**Comment by JDWoodcock** [comment]
i found it sometimes works sometimes got nowhere-  mainly crashing as I tried to load region. So landing page ok but then nothing more.

**Comment by JDWoodcock** [comment]
i am now on train so dodgy internet hence no use testing further. 
but these problems were back in the office. Ali was getting similar @usr110 - he suggested there are two servers one working one not, so depends which one you connect to

**Comment by Robinlovelace** [comment]
I think it may be due to dodgy train connection so closing for now. Please re-test when you have a good internet connection and re-open if you're having issues. Closing as not (currently) reproducible - but interested to see what the logs say.

**Comment by RachelAldred** [comment]
Hi Robin - can we leave open? It wasn't just a problem with the train, James and Ali also experienced it in the office, and Megan and I did working on stable internet connections too. Thanks.

**Comment by JDWoodcock** [comment]
yes please - I wouldnt have posted based on train connection. I just said I can't test while on train.

**Comment by Robinlovelace** [comment]
Sure. Please post steps to reproduce and we can look into it.

**Comment by RachelAldred** [comment]
I think the whole problem is sometimes it crashes sometimes it doesn't. E.g. using IE I just did the following:

Went to http://www.pct.bike/m/?r=london (ok)
Clicked on the clickable route network option under Cycling Flows (ok)
Turned flows up to 90% (ok)
Zoomed into East London

When I zoomed in it then quickly disconnected from the server.

**Comment by JDWoodcock** [comment]
I opened PCT. I clicked on Cambridgeshire . I waited. It crashed. This was error message (back in office)
ok now getting this for Cambridgeshire
Mon Jul 15 2019 15:52:16 GMT+0100 (British Summer Time) [INF]: Connection opened. http://pct.bike/m/?r=cambridgeshire shiny-server-client.min.js:1:21781
Mon Jul 15 2019 15:52:16 GMT+0100 (British Summer Time) [DBG]: Open channel 0 shiny-server-client.min.js:1:5353
The application unexpectedly exited.

Diagnostic information is private. Please ask your system admin for permission if you need to check the R logs. shiny-server-client.min.js:1:24931
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [INF]: Connection closed. Info: {"type":"close","code":4503,"reason":"The application unexpectedly exited","wasClean":true} shiny-server-client.min.js:1:21781
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [DBG]: SockJS connection closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [DBG]: Channel 0 is closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 15:52:17 GMT+0100 (British Summer Time) [DBG]: Removed channel 0, 0 left shiny-server-client.min.js:1:5353

**Comment by Robinlovelace** [comment]
Still cannot reproduce it. But see there is an issue - will await server logs from @nikolai-b - can take a look but volunteering in Pedallers until 8pm and then got footy 'till 10pm so won't be for a while. Apolz for jumping the gun on closing this pesky issue. What % of time does it fail on? Currently for me it's zero but have only tried ~5 times today.

**Comment by JDWoodcock** [comment]
i just tried twice in firefox private browsing and chrome- and could not get London to load at all.

**Comment by JDWoodcock** [comment]
i think we should distinguish stress testing- schools layer on max for London (which is always slow) with just not working. I am having more of the just not working problem.

**Comment by usr110** [comment]
Can reproduce the error at home too - using `london`. It shows up as soon as you interact with the app - make any changes with the input.

```
The application unexpectedly exited.



Diagnostic information is private. Please ask your system admin for permission if you need to check the R logs. shiny-server-client.min.js:1:24931
Mon Jul 15 2019 19:22:01 GMT+0100 (British Summer Time) [INF]: Connection closed. Info: {"type":"close","code":4503,"reason":"The application unexpectedly exited","wasClean":true} shiny-server-client.min.js:1:21781
Mon Jul 15 2019 19:22:01 GMT+0100 (British Summer Time) [DBG]: SockJS connection closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 19:22:01 GMT+0100 (British Summer Time) [DBG]: Channel 0 is closed shiny-server-client.min.js:1:5353
Mon Jul 15 2019 19:22:01 GMT+0100 (British Summer Time) [DBG]: Removed channel 0, 0 left shiny-server-client.min.js:1:5353
```


```
TypeError: this.$socket is null
    $sendMsg shinyapp.js:288
    sendInput shinyapp.js:140
    $sendNow input_rate.js:220
    <anonymous> self-hosted:1001
```

**Comment by nikolai-b** [comment]
Very sorry about this.  After the last deployment I noticed a bug in the deploy scripts and made a request to fix but it looks like the cam servers were in some strange state.  There was a problem with the systemd status, systemd is the application that manages shiny-server and is responsible for making sure shiny-server is always running, i.e. if the machine needs to be rebooted.  I've fixed them manually now but please let me know if it works for you all.

If you look at your cookies you can see either:
* `hex_3838` 
* `hex_3839` 
* `cam_3838`
* `cam_3839`

Once this cookie is assigned you will be directed to either the hex (London) server (npt1) or our cam (Cambridge) server (npt2).  If you edit or delete the cookie you can change locations.  The site was working on the `hex` server but not on `cam`.  Here is what the cookie looks like on Firefox:

![Screenshot from 2019-07-15 21-46-20](https://user-images.githubusercontent.com/6289830/61247965-06804980-a74a-11e9-98be-b62444af83ca.png)

**Comment by Robinlovelace** [comment]
Thanks for quick debugging @nikolai-b, explains why it was working on some and not others - and why it never crashed for me leading to me closing the issue. @JDWoodcock and @RachelAldred if you could test again and report back with a 👍 I think we'll finally be able to close this. Any ideas what caused the crash on the `cam` server?

**Comment by JDWoodcock** [comment]
thanks a lot @nikolai-b it seems to be working. A bit slow but fingers crossed will be ok with about 20 people working on it today at UofW.

**Comment by Robinlovelace** [comment]
Best of luck with the course. Hope it goes well, and keep us updated of any further issues.

**Comment by JDWoodcock** [comment]
oh dear still getting some problems. Sometimes just not loading the page at all @nikolai-b

**Comment by JDWoodcock** [comment]
not working at all @nikolai-b @Robinlovelace . Can't get past landing page. Trying multiple incognito windows.

**Comment by usr110** [comment]
@nikolai-b 

thanks for working on this - again. I am afraid it doesn't seem to work even for `london` servers. See below:

![image](https://user-images.githubusercontent.com/10958628/61290634-3d934100-a7c4-11e9-9d9e-8ecdcce9f6f5.png)

**Comment by RachelAldred** [comment]
Yes I cannot get it to work at all. I gave the trainees an early lunch break - they return in 20 mins and currently my plan is to give everyone the test server URL and get them to use that.

**Comment by nikolai-b** [comment]
Really sorry, I've restarted both servers, no idea why this is happening.  They should work on live now.

**Comment by usr110** [comment]
> Really sorry, I've restarted both servers, no idea why this is happening. They should work on live now.

Seems to be working fine now at my end. Thanks a bunch @nikolai-b 

I guess the solution to all IT problems boils down to "have you tried switch it off and on again?"

**Comment by JDWoodcock** [comment]
hmm. it was working for a bit but we are now getting problems again and the test server is having trouble too! @nikolai-b

**Comment by Robinlovelace** [comment]
@nikolai-b could it be worth reverting the memory-saving fix, where it keeps the most recent region data in memory, to see if that helps? Just a thought.

**Comment by JDWoodcock** [comment]
there were quite a few problems yesterday- I will send an email @nikolai-b @Robinlovelace

**Comment by Robinlovelace** [comment]
Update: the bug that was definitely causing crashes was fixed in #761 so closing for now. However, we will monitor the situation and look into ways of improving performance. @nikolai-b and I tested load times for London LSOA level and it's very slow the 1st time, then levels off. 

That's a separate issue. Please check and re-open if there are crashes with the same tests as documented here.

FYI the cause of the crash was actually quite simple and is captured by the reprex below:

``` r
l = list(a = 1, b = 2, c = 3)
index_logical = c(FALSE, FALSE, TRUE)
l[[index_integer]]
#> Error in eval(expr, envir, enclos): object 'index_integer' not found
```

Which can be fixed by converting the logical vector into an integer number:

```r
index_integer = which(index_logical)
l[[index_integer]]
#> [1] 3
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note @nikolai-b (just as a follow-up) `[[` returns the contents of the list whereas `[` returns a list, making `[[` usually the preferred choice for working with the contents of a list and better stylistically (hence https://github.com/npct/pct-shiny/pull/762 ) , even though it seems to make no difference in practice in this case.

**Comment by Robinlovelace** [comment]
Follow-up below. Please re-open if the issues reported in this thread appear again.

``` r
l = list(a = 1, b = 2, c = 3)
index_logical = c(FALSE, FALSE, TRUE)
index_integer = which(index_logical)
class(l[[index_integer]]) # this is what we want
#> [1] "numeric"
class(l[index_integer]) # this isn't
#> [1] "list"
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by RachelAldred** [comment]
Not working again - spinner and grey screen.

**Comment by Robinlovelace** [comment]
Working for me in West Yorkshire  and London although slow. Can you try navigating here and let us know if it's still down? Wondering if one of the servers is down again:

http://www.pct.bike/m/?r=london

http://www.pct.bike/m/?r=west-yorkshire

Any ideas @nikolai-b ?

**Comment by Robinlovelace** [comment]
These are the latest server logs:

```
Warning in readLines(file.path(interface_root, "outputs_regional_sha")) :
  incomplete final line found on '../../outputs_regional_sha'
Warning in is.na(expression) :
  is.na() applied to non-(list or vector) of type 'NULL'
Warning: Error in round: non-numeric argument to mathematical function
  55: round_dp
  53: negative_red
  52: popup_destinations
  44: <observer> [/var/shiny/pct-shiny/regions_www/m/server.R#720]
   1: runApp e_redWarning in is.na(expression) :
  52: popup_destinations is.na() applied to non-(list or vector) of type 'NULL' Warning: Error in round: non-numeric argument to mathematical function
  44: <observer> [/var/shiny/pct-shiny/regions_www/m/server.R#720] 55: round_dp
   1: runApp 53: negative_red Warning in is.na(expression) : 52: popup_destinations
  is.na() applied to non-(list or vector) of type 'NULL' 44: <observer> [/var/shiny/pct-shiny/regions_www/m/server.R#720] Warning: Error in round: non-numeric argument
to mathematical function 1: runApp
  55: round_dp
  53: negative_red
  52: popup_destinations
  44: <observer> [/var/shiny/pct-shiny/regions_www/m/server.R#720]
   1: runApp

```

**Comment by JDWoodcock** [comment]
currently working for me though a little slow

**Comment by nikolai-b** [comment]
That looks like a problem we should be able to reproduce locally: 
https://github.com/npct/pct-shiny/issues/759#issuecomment-512853445

I've spent 30mins clicking in the app but I can't reproduce that error.  It looks like some data might be `NULL` somewhere we don't expect.

**Comment by Robinlovelace** [comment]
I think that is a separate issue. Suggest closing this one and opening a new one, unless anyone objects.

**Comment by Robinlovelace** [comment]
I do, but would like to check with @nikolai-b before announcing, and closing this issue.

**Comment by nikolai-b** [comment]
Yes, I don't see any more errors.  If we do get another problem it makes sense to open up another issue as there have been multiple things that have gone wrong (all resulting in reduced server reliability).
